package top.infra.maven.extension;

public abstract class Orders {

    public static final int CI_OPTION_FAST = Ordered.HIGHEST_PRECEDENCE;
    public static final int CI_OPTION_INFRA = CI_OPTION_FAST + 1;
    public static final int CI_OPTION_MAVEN_BUILD_EXTENSION = CI_OPTION_INFRA + 1;
    public static final int CI_OPTION_MAVEN = CI_OPTION_MAVEN_BUILD_EXTENSION + 1;
    public static final int CI_OPTION_DOCKER = CI_OPTION_MAVEN + 1;
    public static final int CI_OPTION_GPG = CI_OPTION_DOCKER + 1;
    public static final int CI_OPTION_MAVEN_BUILD_POM = CI_OPTION_GPG + 1;

    public static final int CONFIGURATION_PROCESSOR_ORDER_PRINT_INFO = Ordered.HIGHEST_PRECEDENCE;
    public static final int CONFIGURATION_PROCESSOR_ORDER_SYSTEM_TO_USER_PROPERTIES = CONFIGURATION_PROCESSOR_ORDER_PRINT_INFO + 1;
    public static final int CONFIGURATION_PROCESSOR_ORDER_OPTIONS_FACTORY = CONFIGURATION_PROCESSOR_ORDER_SYSTEM_TO_USER_PROPERTIES + 1;
    public static final int CONFIGURATION_PROCESSOR_ORDER_OPTION_FILE_LOADER = CONFIGURATION_PROCESSOR_ORDER_OPTIONS_FACTORY + 1;

    public static final int EVENT_AWARE_ORDER_CI_OPTION = CONFIGURATION_PROCESSOR_ORDER_SYSTEM_TO_USER_PROPERTIES + 1;
    public static final int EVENT_AWARE_ORDER_MAVEN_SETTINGS_LOCALREPOSITORY = EVENT_AWARE_ORDER_CI_OPTION + 1;
    public static final int EVENT_AWARE_ORDER_MAVEN_SETTINGS_FILES = EVENT_AWARE_ORDER_MAVEN_SETTINGS_LOCALREPOSITORY + 1;
    // ORDER_MAVEN_SETTINGS_LOCALREPOSITORY + 1;
    public static final int EVENT_AWARE_ORDER_MAVEN_SETTINGS_SERVERS = EVENT_AWARE_ORDER_MAVEN_SETTINGS_FILES + 1;
    public static final int EVENT_AWARE_ORDER_MODEL_RESOLVER = EVENT_AWARE_ORDER_MAVEN_SETTINGS_SERVERS + 1;
    public static final int EVENT_AWARE_ORDER_GPG = EVENT_AWARE_ORDER_MODEL_RESOLVER + 1;
    public static final int EVENT_AWARE_ORDER_MAVEN_PROJECT_INFO = EVENT_AWARE_ORDER_GPG + 1;
    public static final int EVENT_AWARE_ORDER_GOAL_EDITOR = EVENT_AWARE_ORDER_MAVEN_PROJECT_INFO + 1;
    public static final int EVENT_AWARE_ORDER_DOCKER = EVENT_AWARE_ORDER_GOAL_EDITOR + 1;

    private Orders() {
    }
}
